--INICIO Y FIN DE TRANSACCIONES (TAMBIEN PARA LOS BLOQUEOS)
    --DDL inicio y fin (CREATE TABLE, ALTER TABLE, DROP TABLE...)
    --COMMIT cierra transaccion
    --ROLLBACK cierra transaccion
    --ROLLBACK TO SAFEPOINT vuelve atras pero no cierra
    
    --NIVELES DE AISLAMIENTO
--READ COMMITED => SOLO SE VEN LOS CAMBIOS QUE SON CONFIRMADOS
--SERIALIZABLE => VE LOS DATOS TAL CUAL ESTABAN AL INICIAR LA TRANSACCION
    --READ ONLY => Es serializable PERO SOLO SE PUEDE LEER, NO SE PUEDE MODIFICAR LA BBDD